// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"filestore-server/service/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ReqSignup  = user.ReqSignup
	RespSignup = user.RespSignup

	User interface {
		Signup(ctx context.Context, in *ReqSignup, opts ...grpc.CallOption) (*RespSignup, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Signup(ctx context.Context, in *ReqSignup, opts ...grpc.CallOption) (*RespSignup, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Signup(ctx, in, opts...)
}
