// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"filestore-server/service/user/internal/logic"
	"filestore-server/service/user/internal/svc"
	"filestore-server/service/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Signup(ctx context.Context, in *user.ReqSignup) (*user.RespSignup, error) {
	l := logic.NewSignupLogic(ctx, s.svcCtx)
	return l.Signup(in)
}
